version: '3.8'

volumes:
  postgres_data: 

services:
  postgres:
    restart: unless-stopped
    image: postgres:13.11-bullseye
    container_name: corserva_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER} 
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
