version: '3.8'

volumes:
  postgres_data: 

services:
  postgres:
    restart: unless-stopped
    image: postgres:13.11-bullseye
    container_name: corserva_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER} 
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  corserva_app:
    restart: unless-stopped
    container_name: corserva_backend
    image: corserva
    depends_on:
      - postgres
    build:
      context: .
      target: prod
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      PORT: ${PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
